version: '3'
services:
  front_end:
    container_name: front-end-container
    image: front-end-image
    build: ./front-end
    # environment:
    #   - API_URL=back_end/sla
    # depends_on:
    #   - back_end
    ports:
      - "3015:3015"
  dbservice:
    container_name: mongodbservicecontainer
    image: mongo
    ports:
      - "27017:27017"
  back_end:
    container_name: back-end-container
    image: back-end-image
    build: ./back-end
    environment:
      - MONGO_HOSTS=dbservice
    depends_on: 
      - dbservice
    ports:
      - "3000:3000"
  
  # nginx:
  #   container_name: nginxservicecontainer
  #   image: nginx:alpine
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./front-end/build:/srv/www/static
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - front_end
  #     - back_end  
# volumes:  
#   front_end_public:./front-end/build



